### ISSUE TITLE
Create Admin Page / Carousel Item

### ISSUE THREAD

**Issue by radistoubalidis** [ADOPSE-Team17/not-imdb-backend#36]
Admin Page
- Layout similar to google settings (συντομα και καποια sample ελπιζουμε)
- Movie Management
- Search Bar (εστω οτι δουλευει κανονικα)
       1. Ο admin θα εισαγει ενα query ( πχ star {...} ) και θα του εμφανιζονται τα καταλληλα αποτελεσματα σε μορφη v-card
       2. θα επιλεγει την ταινια που θελει να τροποποιησει και αφου κανει κλικ θα ανοιγει ενα drop-down window στο οποιο θα         εμφανιζεται το page της ταινιας περιπου οπως εμφανιζεται και στον χρηστη για να κανει τις τροποποιησεις του
       3. Στο κατω μετος του window θα υπαρχει ενα toolbar στο οποιο ο admin θα επισημοποιει τις αλλαγες του μαζι με ενα κουμπι save changes
       4. Θα υπαρχει η δυνατοτητα να δει ο admin την σελιδα οπως θα εμφνιζεται στον χρηστη

- Σχεδιαση των item (ταινιες) που θα υπαρχουν στα carousel

**Comment by radistoubalidis** [comment]
Fixed the build error. @dPliakos can you review the latest merge of components weith master show I can close the issue ?

**Comment by dPliakos** [comment]
Fixed in https://github.com/ADOPSE-Team17/not-imdb-backend/pull/39
