### ISSUE TITLE
Vue router does not respect the /client base url

### ISSUE THREAD

**Issue by dPliakos** [ADOPSE-Team17/not-imdb-backend#50]
The vue-router does not respect the `/client` base url as it's set in nuxtconfig.js

Components are stacking when the `/client` route is being used.
e.g. When the `/client/Login` route is being used, I see both Login and Index components

**Comment by Mr-Watch** [comment]
The buttons use the href tag... so the framework can't work out the route. If one wraps the button with a nuxt-link and point it to the /Register it works. Although I don't think that is the most elegant solution.
