### ISSUE TITLE
Create the user authentication endpoints

### ISSUE THREAD

**Issue by dPliakos** [ADOPSE-Team17/not-imdb-backend#8]
Create the `Auth` controller for the user authentication management.

Expected endpoints:
- `/Auth/Register` (POST): It should create a new user account with local credentials
 - `/Auth/Login` (POST): It should authenticate a user and return a JWT
 - `/Auth/Logout` (POST): It could be a dummy endpoint if the JWT invalidation is not supported by the authenticationService

> Depends on #4

**Comment by dPliakos** [comment]
Blocks #28

**Comment by radistoubalidis** [comment]
got it , will work on it tomorrow

**Comment by dPliakos** [comment]
@radistoubalidis I'm working on it , sorry I assigned it to you by accident

**Comment by dPliakos** [comment]
@DimitrisR92 I created the authentication endpoints in #35. You can use those to apply the authentication code.

I added an example for the user login, that it just returns the user on a success match. I'm assigning this issue to you

**Comment by dPliakos** [comment]
Fixed by #35
